***CHARMI YASHWANT KANANI***

***GO_STP_755***

**Assignment/Task 5**

Pandas - Data Analysis of IMDB movies data
As we have a basic understanding of the different data structures in Pandas, let’s explore the fun and interesting ‘IMDB-movies-dataset’ and get our hands dirty by performing practical data analysis on real data.
It is an open-source dataset.

We will read the data from the .csv file and perform the following basic operations on movies data.

In [1]:
import numpy as np
import pandas as pd

1. Load the IMDb Dataset and read
2. View the dataset

In [2]:
df = pd.read_csv("IMDB-Movie-Data.csv")
df.head(2)

   Rank                    Title  ... Revenue (Millions) Metascore
0     1  Guardians of the Galaxy  ...             333.13      76.0
1     2               Prometheus  ...             126.46      65.0

[2 rows x 12 columns]

In [3]:
df.tail(2)

     Rank         Title  ... Revenue (Millions) Metascore
998   999  Search Party  ...                NaN      22.0
999  1000    Nine Lives  ...              19.64      11.0

[2 rows x 12 columns]

3. Understand some basic information about the dataset and Inspect the dataframe Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [5]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [6]:
df.shape

(1000, 12)

In [7]:
df.size

12000

In [8]:
df.ndim

2

In [9]:
df.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
        'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
        'Metascore'],
       dtype='object')]

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.describe()

              Rank         Year  ...  Revenue (Millions)   Metascore
count  1000.000000  1000.000000  ...          872.000000  936.000000
mean    500.500000  2012.783000  ...           82.956376   58.985043
std     288.819436     3.205962  ...          103.253540   17.194757
min       1.000000  2006.000000  ...            0.000000   11.000000
25%     250.750000  2010.000000  ...           13.270000   47.000000
50%     500.500000  2014.000000  ...           47.985000   59.500000
75%     750.250000  2016.000000  ...          113.715000   72.000000
max    1000.000000  2016.000000  ...          936.630000  100.000000

[8 rows x 7 columns]

4. Data Selection – Indexing and Slicing data

In [12]:
df['Rating']

0      8.1
1      7.0
2      7.3
3      7.2
4      6.2
      ...
995    6.2
996    5.5
997    6.2
998    5.6
999    5.3
Name: Rating, Length: 1000, dtype: float64

In [13]:
df[['Rating', 'Revenue (Millions)', 'Metascore']]

     Rating  Revenue (Millions)  Metascore
0       8.1              333.13       76.0
1       7.0              126.46       65.0
2       7.3              138.12       62.0
3       7.2              270.32       59.0
4       6.2              325.02       40.0
..      ...                 ...        ...
995     6.2                 NaN       45.0
996     5.5               17.54       46.0
997     6.2               58.01       50.0
998     5.6                 NaN       22.0
999     5.3               19.64       11.0

[1000 rows x 3 columns]

In [14]:
df[51:61]

    Rank                               Title  ... Revenue (Millions) Metascore
51    52              Underworld: Blood Wars  ...              30.35      23.0
52    53                        Mother's Day  ...              32.46      18.0
53    54                           John Wick  ...              43.00      68.0
54    55                     The Dark Knight  ...             533.32      82.0
55    56                             Silence  ...               7.08      79.0
56    57                       Don't Breathe  ...              89.21      71.0
57    58                       Me Before You  ...              56.23      51.0
58    59                        Their Finest  ...               3.18      76.0
59    60                               Sully  ...             125.07      74.0
60    61  Batman v Superman: Dawn of Justice  ...             330.25      44.0

[10 rows x 12 columns]

In [15]:
df.iloc[11:21,[8,10,11]]

    Rating  Revenue (Millions)  Metascore
11     7.8              169.27       74.0
12     7.9              532.17       65.0
13     7.7              248.75       81.0
14     6.4                2.87       70.0
15     6.6              368.31       61.0
16     8.2               67.12       71.0
17     6.7              162.16       58.0
18     8.1               51.69       69.0
19     8.0              100.50       81.0
20     6.7                7.22       49.0

5. Data Selection – Based on Conditional filtering

In [16]:
s = df[df['Rating']> 8.0]
s.shape

(59, 12)

In [17]:
len(df[(df['Rating']>8.0) & (df['Metascore']>=75.0)])

33

6. Groupby operations

In [18]:
g = df.groupby('Director')
g[['Revenue (Millions)']].median().sort_values('Revenue (Millions)',ascending = False).head()

                 Revenue (Millions)
Director
James Cameron               760.510
Colin Trevorrow             652.180
Joss Whedon                 541.135
Lee Unkrich                 414.980
Gary Ross                   408.000

In [19]:
df.groupby('Director')[['Runtime (Minutes)', 'Revenue (Millions)','Rating', 'Votes']].mean().sort_values('Votes',ascending = False).head()

                   Runtime (Minutes)  Revenue (Millions)  Rating      Votes
Director
Christopher Nolan              152.6             303.018    8.68  1311817.0
James Cameron                  162.0             760.510    7.80   935408.0
Joss Whedon                    142.0             541.135    7.75   781241.5
Quentin Tarantino              154.5             112.480    7.90   639896.5
Tim Miller                     108.0             363.020    8.00   627797.0

7. Sorting operation

In [20]:
df.sort_values(by = ['Rating', 'Votes'], ascending = [False, False])

     Rank                    Title  ... Revenue (Millions) Metascore
54     55          The Dark Knight  ...             533.32      82.0
80     81                Inception  ...             292.57      74.0
117   118                   Dangal  ...              11.15       NaN
36     37             Interstellar  ...             187.99      74.0
249   250         The Intouchables  ...              13.18      57.0
..    ...                      ...  ...                ...       ...
890   891               The Intent  ...                NaN      59.0
647   648                 Tall Men  ...                NaN      57.0
871   872     Dragonball Evolution  ...               9.35      45.0
42     43  Don't Fuck in the Woods  ...                NaN       NaN
829   830           Disaster Movie  ...              14.17      15.0

[1000 rows x 12 columns]

8. Dealing with missing values

In [21]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [22]:
df['Revenue (Millions)'].fillna(df['Revenue (Millions)'].median(),inplace=True)
df.isnull().sum()

Rank                   0
Title                  0
Genre                  0
Description            0
Director               0
Actors                 0
Year                   0
Runtime (Minutes)      0
Rating                 0
Votes                  0
Revenue (Millions)     0
Metascore             64
dtype: int64

9. Dropping columns and null values

In [23]:
df.dropna(inplace = True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 936 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                936 non-null    int64
 1   Title               936 non-null    object
 2   Genre               936 non-null    object
 3   Description         936 non-null    object
 4   Director            936 non-null    object
 5   Actors              936 non-null    object
 6   Year                936 non-null    int64
 7   Runtime (Minutes)   936 non-null    int64
 8   Rating              936 non-null    float64
 9   Votes               936 non-null    int64
 10  Revenue (Millions)  936 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 95.1+ KB

In [25]:
del df['Rank']

In [26]:
df.columns

Index(['Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

10. Apply( ) functions

In [27]:
def in_hours(rt):
  hr = rt/60
  return hr.round(2)

In [28]:
df[['Runtime (Minutes)']].apply(in_hours)

     Runtime (Minutes)
0                 2.02
1                 2.07
2                 1.95
3                 1.80
4                 2.05
..                 ...
995               1.85
996               1.57
997               1.63
998               1.55
999               1.45

[936 rows x 1 columns]